# some more ls aliases
alias ll='ls -alF'
alias la='ls -A' 
alias l='ls -CF'

# git aliases
alias ga='git add'
alias gb='git branch' 
alias gbd='git branch -d'
alias gbD='git branch -D'
alias gc='git checkout'
alias gcb='git checkout -b'
alias gcm='git commit -m'
alias gcn='git commit -n -m'
alias gd='git diff'
alias gds='git diff --staged'
alias gf='git fetch'
alias gg='git grep'
alias gl='git log'
alias gm='git merge'
alias gmv='git move'
alias gpo='git pull origin'
alias gpso='git push origin'
alias gr='git restore'
alias grs='git restore --staged'
alias grb='git rebase'
alias grm='git rm'
alias gs='git status'
alias gsh='git show'
alias gst='git stash'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gstd='git stash drop'

